# title of website
title:   

# description of website
description: unyu's navigation site

# favicon of website
favicon: "https://github.com/unyu.png?size=40"

# your website url
# url: https://unyu.github.io/nav/

# github profile url
# github: "https://github.com/unyu"

# footer message
# footer: © 2021-2021 @unyu

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: v2ex
          description: 创意工作者们的社区
          url: https://www.v2ex.com/
        - name: 少数派
          description: 高效工作 品质生活
          url: https://sspai.com/
        - name: 国家税务
          description: 北京电子税务局
          url: https://etax.beijing.chinatax.gov.cn/         
    - name: 影视
      sites:
        - name: 中国高清网
          url: http://gaoqing.la/
        - name: 低端影视
          description: 超清在线视频站
          url: https://ddrk.me/
        - name: LIBVIO影视
          description: 超清在线视频站
          url: https://www.libvio.cc/
        - name: 厂长资源
          description: 在线免费播放_最新高清电影_美剧推荐_日韩剧集推荐！
          url: https://czzy03.com/
        - name: 影猫の仓库
          description: 免费观影第一站！
          url: https://ymck.me/
        - name: 好看的美剧
          url: http://www.meijutt.com/
        - name: 预告片世界
          url: http://www.yugaopian.cn/
    - name: 工具
      sites:
        - name: 图片压缩
          description: 图片压缩
          url: https://squoosh.app/
        - name: iLoveIMG | 图像文件在线编辑工具
          description: iLoveIMG | 图像文件在线编辑工具
          url: https://www.iloveimg.com/zh-cn
        - name: 消除或者替换图像背景，无需上传图像 - BgSub
          description: 消除或者替换图像背景，无需上传图像
          url: https://bgsub.cn/webapp/
        - name: Convertio — 文件转换器
          description: Convertio — 文件转换器
          url: https://convertio.co/zh/
        - name: Smallpdf.com – 您所有 PDF 问题的免费解决方案
          description: Smallpdf.com – 您所有 PDF 问题的免费解决方案
          url: https://smallpdf.com/cn
        - name: 在线转换文档，图像，视频，音频文件
          description: 在线转换文档，图像，视频，音频文件
          url: https://www.aconvert.com/cn/
        - name: Regex.ai 正则工具箱
          description: Regex.ai 正则工具箱
          url: https://regex.ai/
        - name: 在线文本差异对比
          description: 在线文本差异对比
          url: http://www.jq22.com/textDifference
        - name: ProcessOn
          description: ProcessOn
          url: https://www.processon.com/
        - name: 自定义地图 | 高德地图 API
          description: 自定义地图 | 高德地图 API
          url: https://lbs.amap.com/getting-started/mapstyle
        - name: 短信平台 Virtual numbers for receiving SMS online - SMS-Activate
          description: 短信平台 Virtual numbers for receiving SMS online - SMS-Activate
          url: https://sms-activate.org/en
        - name: 工具人 - TOOLFK 在线工具人
          description: 工具人 - TOOLFK 在线工具人
          url: https://www.toolfk.com/
        - name: 种子转磁力
          description: 种子转磁力
          url: https://instant.io/
        - name: 大数据导航 - 大数据工具导航 -199IT 大数据导航 -199IT 大数据工具导航 -Hao.199it.com
          description: 大数据导航 - 大数据工具导航 -199IT 大数据导航 -199IT 大数据工具导航 -Hao.199it.com
          url: http://hao.199it.com/
        - name: 淘声网 - toSound 声音搜索引擎 - 免费音效素材资源 | 视频游戏配乐下载
          description: 淘声网 - toSound 声音搜索引擎 - 免费音效素材资源 | 视频游戏配乐下载
          url: https://www.tosound.com/
        - name: 字体下载 - 求字体网提供中文和英文字体库下载、识别与预览服务，找字体的好帮手
          description: 字体下载 - 求字体网提供中文和英文字体库下载、识别与预览服务，找字体的好帮手
          url: https://www.zhaozi.cn/
        - name: 找字网 _ 找字体、免费字体下载、字体在线商用授权、ttf 字体分享、专业字体网站！
          description: 找字网 _ 找字体、免费字体下载、字体在线商用授权、ttf 字体分享、专业字体网站！
          url: https://www.china-font.net/
        - name: 爱给网 _ 音效配乐 _3D 模型 _ 视频素材 _ 免费下载
          description: 爱给网 _ 音效配乐 _3D 模型 _ 视频素材 _ 免费下载
          url: https://www.aigei.com/
        - name: ppt - MindShow，让想法快速展示
          description: ppt - MindShow，让想法快速展示
          url: https://www.mindshow.fun
        - name: 在线视频下载 - VideoFk
          description: 在线视频下载 - VideoFk
          url: https://www.videofk.com/zh-CN/online-video-download
        - name: SkrBT - 专业的种子搜索、磁力链接搜索引擎
          description: SkrBT - 专业的种子搜索、磁力链接搜索引擎
          url: https://skrbtge.top/
        - name: 路过图床 - 免费图片上传, 专业图片外链, 免费公共图床
          description: 路过图床 - 免费图片上传, 专业图片外链, 免费公共图床
          url: https://imgse.com/
        - name: AlternativeTo - Crowdsourced software recommendations
          description: AlternativeTo - Crowdsourced software recommendations
          url: https://alternativeto.net/
        - name: waifu2x
          description: waifu2x
          url: https://waifu2x.udp.jp/
        - name: 帮小忙 - 腾讯 QQ 浏览器在线工具箱平台
          description: 帮小忙 - 腾讯 QQ 浏览器在线工具箱平台
          url: https://tool.browser.qq.com/

    - name: 社区资讯
      sites:
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/

    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: Icon Archive
          description: Search 590,912 free icons
          url: http://www.iconarchive.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: ion icons
          description: The premium icon font for Ionic Framework.
          url: http://ionicons.com/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
