# title of website
title:   

# description of website
description: unyu's navigation site

# favicon of website
favicon: "https://github.com/unyu.png?size=40"

# your website url
# url: https://unyu.github.io/nav/

# github profile url
# github: "https://github.com/unyu"

# footer message
# footer: © 2021-2021 @unyu

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: v2ex
          description: 创意工作者们的社区
          url: https://www.v2ex.com/
        - name: 少数派
          description: 高效工作 品质生活
          url: https://sspai.com/
        - name: 国家税务
          description: 北京电子税务局
          url: https://etax.beijing.chinatax.gov.cn/         
          
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 猎云网
          description: 互联网创业项目推荐和创业创新资讯
          url: http://www.lieyunwang.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/

    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: Icon Archive
          description: Search 590,912 free icons
          url: http://www.iconarchive.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: ion icons
          description: The premium icon font for Ionic Framework.
          url: http://ionicons.com/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: 平面素材
      sites:
        - name: wallhalla
          description: Find awesome high quality wallpapers for desktop and mobile in one place.
          url: https://wallhalla.com/
        - name: 365PSD
          description: Free PSD & Graphics, Illustrations
          url: https://365psd.com/
        - name: Medialoot
          description: Free & Premium Design Resources — Medialoot
          url: https://medialoot.com/
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/
        - name: 千库网
          description: 免费png图片背景素材下载
          url: http://588ku.com/
        - name: 我图网
          description: 我图网,提供图片素材及模板下载,专注正版设计作品交易
          url: http://www.ooopic.com/
        - name: 90设计
          description: 电商设计（淘宝美工）千图免费淘宝素材库
          url: http://90sheji.com/
        - name: 昵图网
          description: 原创素材共享平台
          url: http://www.nipic.com/
        - name: 素材中国
          description: 免费素材共享平台
          url: http://www.sccnn.com/
        - name: freepik
          description: More than a million free vectors, PSD, photos and free icons.
          url: https://www.freepik.com/
    - name: UI资源
      sites:
        - name: Freebiesbug
          description: Hand-picked resources for web designer and developers, constantly updated.
          url: https://freebiesbug.com/
        - name: Freebie Supply
          description: Free Resources For Designers
          url: https://freebiesupply.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: ui8
          description: UI Kits, Wireframe Kits, Templates, Icons and More
          url: https://ui8.net/
        - name: PrincipleRepo
          description: Free, High Quality Principle Resources
          url: http://principlerepo.com/
        - name: Designmodo
          description: Web Design Blog and Shop
          url: https://designmodo.com/
    - name: 字体资源
      sites:
        - name: Google Font
          description: Making the web more beautiful, fast, and open through great typography
          url: https://fonts.google.com/
        - name: Typekit
          description: Quality fonts from the world’s best foundries.
          url: https://typekit.com/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/
        - name: Fontsquirrel
          description: FREE fonts for graphic designers
          url: https://www.fontsquirrel.com/
        - name: Urban Fonts
          description: Download Free Fonts and Free Dingbats.
          url: https://www.urbanfonts.com/
        - name: Lost Type
          description: Lost Type is a Collaborative Digital Type Foundry
          url: http://www.losttype.com/
        - name: Fontex
          description: Free Fonts to Download + Premium Typefaces
          url: http://www.fontex.org/
        - name: FontM
          description: Free Fonts
          url: http://fontm.com/
        - name: My Fonts
          description: Fonts for Print, Products & Screens
          url: http://www.myfonts.com/
        - name: Da Font
          description: Archive of freely downloadable fonts.
          url: https://www.dafont.com/
        - name: OnlineWebFonts
          description: WEB Free Fonts for Windows and Mac / Font free Download
          url: https://www.onlinewebfonts.com/
        - name: Abstract Fonts
          description: Abstract Fonts (13,866 free fonts)
          url: http://www.abstractfonts.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: 界面设计
      sites:
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Producthunt
          description: 发现新鲜有趣的产品
          url: https://www.producthunt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
        - name: v2ex
          description: 创意工作者们的社区
          url: https://www.v2ex.com/
